services:
  tests:
    image: buildkite/plugin-tester:v4.1.1
    volumes:
      - ".:/plugin"

  lint:
    image: buildkite/plugin-linter:latest
    command: ["--id", "imkarrer/flox-buildkite-plugin"]
    volumes:
      - ".:/plugin"
